### ISSUE TITLE
Error running anodize init

### ISSUE THREAD

**Issue by easybeau** [sidmani/anodize#2]
Hi,

Thanks for this ssg !

I've installed it globally on ubuntu 18.04 but I got an error when I run : anodize init : 

`/usr/lib/node_modules/anodize/node_modules/yargs/yargs.js:1163
      else throw err
           ^

Error: Could not load .anodize.yml, exiting...
    at loadConfig (/usr/lib/node_modules/anodize/src/main.js:12:11)
    at /usr/lib/node_modules/anodize/src/main.js:57:5
    at /usr/lib/node_modules/anodize/node_modules/yargs/lib/middleware.js:57:24
    at Array.reduce (<anonymous>)
    at applyMiddleware (/usr/lib/node_modules/anodize/node_modules/yargs/lib/middleware.js:42:6)
    at Object.runCommand (/usr/lib/node_modules/anodize/node_modules/yargs/lib/command.js:238:19)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/anodize/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/usr/lib/node_modules/anodize/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/usr/lib/node_modules/anodize/src/main.js:60:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
`

If you can help me thank you.

Best regards.

**Comment by sidmani** [comment]
Hi, this project isn't really maintained (I just use it for my website). There are probably numerous bugs which I don't have time to fix. I recommend using a more stable site generator, like Jekyll or Hugo.

**Comment by easybeau** [comment]
Ok thank you for your answer !
